<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>

  <body></body>
  <script>
    class HttpError extends Error {
      constructor(response) {
        super(`${response.status} for ${response.url}`)
        this.name = 'HttpError'
        this.response = response
        console.log('qwe', response)
      }
    }

    async function loadJson(url) {
      let response = await fetch(url)
      if (response.status == 200) {
        return response.json()
      } else {
        throw new HttpError(response)
      }
    }

    // 询问用户名，直到 github 返回一个合法的用户
    async function demoGithubUser() {
      let user
      while (true) {
        let name = prompt('Enter a name?', 'iliakan')

        try {
          user = await loadJson(`https://api.github.com/users/${name}`)
          break // 没有 error，退出循环
        } catch (err) {
          console.log(err)
          // if (err instanceof HttpError && err.response.status == 404) {
          //   // 循环将在 alert 后继续
          //   alert('No such user, please reenter.')
          // } else {
          //   // 未知的 error，再次抛出（rethrow）
          //   throw err
          // }
        }
      }

      alert(`Full name: ${user.name}.`)
      console.log('qwe', user)
      return user
    }

    demoGithubUser()
  </script>
</html>
